require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BirdsoundsController do

  # This should return the minimal set of attributes required to create a valid
  # Birdsound. As you add validations to Birdsound, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BirdsoundsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all birdsounds as @birdsounds" do
      birdsound = Birdsound.create! valid_attributes
      get :index, {}, valid_session
      assigns(:birdsounds).should eq([birdsound])
    end
  end

  describe "GET show" do
    it "assigns the requested birdsound as @birdsound" do
      birdsound = Birdsound.create! valid_attributes
      get :show, {:id => birdsound.to_param}, valid_session
      assigns(:birdsound).should eq(birdsound)
    end
  end

  describe "GET new" do
    it "assigns a new birdsound as @birdsound" do
      get :new, {}, valid_session
      assigns(:birdsound).should be_a_new(Birdsound)
    end
  end

  describe "GET edit" do
    it "assigns the requested birdsound as @birdsound" do
      birdsound = Birdsound.create! valid_attributes
      get :edit, {:id => birdsound.to_param}, valid_session
      assigns(:birdsound).should eq(birdsound)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Birdsound" do
        expect {
          post :create, {:birdsound => valid_attributes}, valid_session
        }.to change(Birdsound, :count).by(1)
      end

      it "assigns a newly created birdsound as @birdsound" do
        post :create, {:birdsound => valid_attributes}, valid_session
        assigns(:birdsound).should be_a(Birdsound)
        assigns(:birdsound).should be_persisted
      end

      it "redirects to the created birdsound" do
        post :create, {:birdsound => valid_attributes}, valid_session
        response.should redirect_to(Birdsound.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved birdsound as @birdsound" do
        # Trigger the behavior that occurs when invalid params are submitted
        Birdsound.any_instance.stub(:save).and_return(false)
        post :create, {:birdsound => {}}, valid_session
        assigns(:birdsound).should be_a_new(Birdsound)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Birdsound.any_instance.stub(:save).and_return(false)
        post :create, {:birdsound => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested birdsound" do
        birdsound = Birdsound.create! valid_attributes
        # Assuming there are no other birdsounds in the database, this
        # specifies that the Birdsound created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Birdsound.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => birdsound.to_param, :birdsound => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested birdsound as @birdsound" do
        birdsound = Birdsound.create! valid_attributes
        put :update, {:id => birdsound.to_param, :birdsound => valid_attributes}, valid_session
        assigns(:birdsound).should eq(birdsound)
      end

      it "redirects to the birdsound" do
        birdsound = Birdsound.create! valid_attributes
        put :update, {:id => birdsound.to_param, :birdsound => valid_attributes}, valid_session
        response.should redirect_to(birdsound)
      end
    end

    describe "with invalid params" do
      it "assigns the birdsound as @birdsound" do
        birdsound = Birdsound.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Birdsound.any_instance.stub(:save).and_return(false)
        put :update, {:id => birdsound.to_param, :birdsound => {}}, valid_session
        assigns(:birdsound).should eq(birdsound)
      end

      it "re-renders the 'edit' template" do
        birdsound = Birdsound.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Birdsound.any_instance.stub(:save).and_return(false)
        put :update, {:id => birdsound.to_param, :birdsound => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested birdsound" do
      birdsound = Birdsound.create! valid_attributes
      expect {
        delete :destroy, {:id => birdsound.to_param}, valid_session
      }.to change(Birdsound, :count).by(-1)
    end

    it "redirects to the birdsounds list" do
      birdsound = Birdsound.create! valid_attributes
      delete :destroy, {:id => birdsound.to_param}, valid_session
      response.should redirect_to(birdsounds_url)
    end
  end

end
